// Generated by CoffeeScript 1.6.3
var User, mongoose;

mongoose = require('mongoose');

User = new mongoose.Schema({
  s: String,
  body: String,
  url: String
});

module.exports = mongoose.model('User', User);
